language: rust

notifications:
  email:
    on_success: never
    on_failure: always

install:
  - sudo apt-get update
  - sudo apt-get install libsdl1.2-dev

script:
  - cargo build
  - cargo build --release
  - cargo test